# Tensors

Similar to arrays and matrices

Use: encode the inputs and outputs of a model as well as the parameters



In [1]:
import torch
import numpy as np

You can create a tensor directly from data


In [2]:
data=[[1,2,3,4],[5,6,7,8]]
x_data=torch.tensor(data)

or from a numpy array

In [3]:
array=np.array(data)
x_array=torch.from_numpy(array)
print(f"Data Tensor: \n{x_data}\n")

Data Tensor: 
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])



In [4]:
# or from other tensors
x_ones=torch.ones_like(x_data)
print(f"Ones Tensor: \n{x_ones}\n")
x_rand=torch.rand_like(x_data,dtype=torch.float)
print(f"Random Tensor: \n{x_rand}\n")

Ones Tensor: 
tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]])

Random Tensor: 
tensor([[0.9647, 0.9820, 0.7648, 0.4157],
        [0.4080, 0.3054, 0.4435, 0.2531]])



In [5]:
shape=(2,9,)

zeros_tensor=torch.zeros(shape)
print(f"Zeros Tensor: \n{zeros_tensor}\n")

Zeros Tensor: 
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]])



### Atributes to a tensor

shape (like above), dtype (data type) or device (where is it running)

In [6]:
tensor=torch.zeros(6,4)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)


torch.Size([6, 4])
torch.float32
cpu


### Operations done on a Tensor

For example: Indexing or slicing

In [7]:
tensor=torch.rand(3,4)
print(f'first row: {tensor[0]}')
print(f'first column: {tensor[:,0]}')
print(f'last column: {tensor[:,-1]}')
print(f"first 3 values of last column: {tensor[:3,-1]}")

first row: tensor([0.2556, 0.0022, 0.0797, 0.4195])
first column: tensor([0.2556, 0.6965, 0.2446])
last column: tensor([0.4195, 0.0975, 0.9062])
first 3 values of last column: tensor([0.4195, 0.0975, 0.9062])


#### Concatenate (Join Tensors)

In [12]:
tensor_1=torch.rand(2,3) 
tensor_2=torch.rand(2,3)
print(tensor_1,'  ')
print(tensor_2)

tensor([[0.4274, 0.4173, 0.3405],
        [0.7125, 0.2025, 0.6864]])   
tensor([[0.9249, 0.6527, 0.9630],
        [0.0840, 0.9048, 0.5200]])


In [13]:

tensor_sum=torch.cat([tensor_1,tensor_2],dim=1)
print(f'Sum Tensor:\n{tensor_sum}')

Sum Tensor:
tensor([[0.4274, 0.4173, 0.3405, 0.9249, 0.6527, 0.9630],
        [0.7125, 0.2025, 0.6864, 0.0840, 0.9048, 0.5200]])


#### Arithmetics

In [9]:
tensor=torch.tensor([[1,2,3],[1,2,3]])
#tensor_2=torch.rand_like(tensor,dtype=torch.float)

#y1=tensor @ tensor.T # matrix multiplication
y2=torch.matmul(tensor,tensor.T) # matrix multiplication
print(y2)
#y3=torch.rand_like(y2)
#torch.matmul(tensor,tensor.T,out=y3) # matrix multiplication


#element-wise product
z1=tensor*tensor
z2=torch.mul(tensor,tensor)
print(z1)
z3=torch.rand_like(z1)
tensor.mul(tensor,tensor,out=z3)

tensor([[14, 14],
        [14, 14]])
tensor([[1, 4, 9],
        [1, 4, 9]])


NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

if you want to change every x value you use a suffix in the formula ex.. tensor.add_()

In [19]:
print(tensor_1)
tensor_1.add_(5)
print(tensor_1)
tensor_1.mul_(.10)
print(tensor_1)

tensor([[104.2740, 104.1731, 103.4051],
        [107.1255, 102.0249, 106.8639]])
tensor([[109.2740, 109.1731, 108.4051],
        [112.1255, 107.0249, 111.8639]])
tensor([[10.9274, 10.9173, 10.8405],
        [11.2125, 10.7025, 11.1864]])
